name: CI-PR

on: [pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules using a PAT
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
    - name: build binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@master
      with:
       name: binary
       path: "code550*"